### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by valkyrienyanko** [valkyrienyanko/Survivor#3]
## MineStone() and MineWood() need to be merged
https://github.com/valkyrienyanko/Survivor/blob/734ffafcf1b0c8346cdcc046a5f9d3e086fd6c75/Assets/Scripts/ColonistAI.cs#L82-L127

**Comment by aeuu** [comment]
Resolved by commit: 1406458d6cf89811c209066fd2c0619d25d58099.
