### ISSUE TITLE
Instant Tracking Lerp

### ISSUE THREAD

**Issue by valkyrienyanko** [valkyrienyanko/Survivor#4]
There is a set duration for when the tracking lerp is set to a lower value, it is then set instantly to a higher value after that duration, it would be nice if rather then instantly it was set gradually to that new value.

https://github.com/valkyrienyanko/Survivor/blob/734ffafcf1b0c8346cdcc046a5f9d3e086fd6c75/Assets/Scripts/CameraController.cs#L104-L110

**Comment by aeuu** [comment]
Resolved by commit: 7acb6811d2b7e3d7e4943b5c574e7c2b8a7a7c2f.
