### ISSUE TITLE
UV Mapping OOP

### ISSUE THREAD

**Issue by valkyrienyanko** [valkyrienyanko/Survivor#50]
UV needs OOP love.

**Comment by aeuu** [comment]
Could you please elaborate on what the issue is?

**Comment by valkyrienyanko** [comment]
https://github.com/valkyrienyanko/Survivor/blob/ffafca05b30a53d9b8369dcb89ac3eba2b9e910e/Assets/Scripts/World/WorldChunk.cs#L67-L90

This part needs to be compressed somehow allowing easier management of loading in textures onto the uvs.

**Comment by valkyrienyanko** [comment]
For example, a Tile class may be needed. Download [this archive](https://github.com/NintendoExaminer/Procedural-Terrain-Generation-Tutorial/blob/master/Procedural%20Terrain%20Generation%20as%20of%20Ep%205.zip) and look at the code to see what I mean.
