### ISSUE TITLE
Randomly Distributed Bases on Grid

### ISSUE THREAD

**Issue by valkyrienyanko** [valkyrienyanko/Survivor#6]
I need a algorithm that will randomly place bases on the 2D world grid spread out from each other at a minimum distance.

See `WorldGeneration.cs`

**Comment by UZ9** [comment]
https://en.wikipedia.org/wiki/Supersampling#Poisson_disc might be worth taking a look at

**Comment by valkyrienyanko** [comment]
https://paste.ofcode.org/zM8rCKHjTHzpMJrbGtuQw3

**Comment by valkyrienyanko** [comment]
https://www.youtube.com/watch?v=7WcmyxyFO7o

**Comment by valkyrienyanko** [comment]
https://github.com/RazorYhang/PoissonDiskGeneratorForUnity

**Comment by valkyrienyanko** [comment]
https://github.com/edcx/Poisson-disc-Sampling
